{% set name = "datasette" %}
{% set version = "0.64.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette-{{ version }}.tar.gz
  sha256: 171e11a213eb747302166c6986487e41f6a9a8847a84fef7861bf88bf1b439b9

build:
  entry_points:
    - datasette = datasette.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - python >=3.7
    - asgiref >=3.2.10
    - click >=7.1.1
    - click-default-group >=1.2.3
    - jinja2 >=2.10.3
    - hupper >=1.9
    - httpx >=0.20
    - pint >=0.9
    - pluggy >=1.0
    - uvicorn >=0.11
    - aiofiles >=0.4
    - janus >=0.6.2
    - asgi-csrf >=0.9
    - pyyaml >=5.3
    - mergedeep >=1.1.1
    - itsdangerous >=1.1
    - setuptools
    - pip

test:
  imports:
    - datasette
  commands:
    - pip check
    - datasette --help
  requires:
    - pip

about:
  home: https://datasette.io/
  summary: An open source multi-tool for exploring and publishing data
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/simonw/datasette
  doc_url: https://docs.datasette.io/en/stable/
  description: |
    Datasette is a tool for exploring and publishing data. It helps people take
     data of any shape or size and publish that as an interactive,
     explorable website and accompanying API. Datasette is aimed at data
     journalists, museum curators, archivists, local governments and anyone else
     who has data that they wish to share with the world. It is part of a wider
     ecosystem of tools and plugins dedicated to making working with structured
      data as productive as possible.

extra:
  recipe-maintainers:
    - thewchan
