{% set name = "datasette" %}
{% set version = "0.61" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette-{{ version }}.tar.gz
  sha256: e08cc5945702b5ea7f002aa9d8b92af8e93da766c811108228843c003fb0015f

build:
  entry_points:
    - datasette = datasette.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - aiofiles <=0.8.0
    - asgi-csrf >=0.9
    - asgiref <=3.4.1
    - click <=8.0.3
    - click-default-group <=1.2.2
    - httpx >=0.21.3
    - hupper >=1.9
    - itsdangerous >=1.1,<3.0
    - janus >=0.6.2,<1.1
    - jinja2 >=2.10.3,<3.1.0
    - markupsafe
    - mergedeep >=1.1.1,<1.4.0
    - pint <=0.17
    - pluggy <=1.0.0
    - python >=3.6
    - python-baseconv <=1.2.2
    - pyyaml >=5.3,<7.0
    - uvicorn <=0.16.0

test:
  imports:
    - datasette
    - datasette.publish
    - datasette.utils
    - datasette.views
  commands:
    - pip check
    - datasette --help
  requires:
    - pip

about:
  home: https://datasette.io/
  summary: An open source multi-tool for exploring and publishing data
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/simonw/datasette
  doc_url: https://docs.datasette.io/en/stable/
  description: |
    Datasette is a tool for exploring and publishing data. It helps people take
     data of any shape or size and publish that as an interactive,
     explorable website and accompanying API. Datasette is aimed at data
     journalists, museum curators, archivists, local governments and anyone else
     who has data that they wish to share with the world. It is part of a wider
     ecosystem of tools and plugins dedicated to making working with structured
      data as productive as possible.

extra:
  recipe-maintainers:
    - thewchan
