{% set name = "datasette" %}
{% set version = "0.64.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette-{{ version }}.tar.gz
  sha256: ee54d87152b2e3e6d4552f157e3431918f5fa929c17afd0548b0d04becbd4c97

build:
  entry_points:
    - datasette = datasette.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - python >=3.7
    - asgiref >=3.2.10
    - click >=7.1.1
    - click-default-group >=1.2.3
    - jinja2 >=2.10.3
    - hupper >=1.9
    - httpx >=0.20
    - pint >=0.9
    - pluggy >=1.0
    - uvicorn >=0.11
    - aiofiles >=0.4
    - janus >=0.6.2
    - asgi-csrf >=0.9
    - pyyaml >=5.3
    - mergedeep >=1.1.1
    - itsdangerous >=1.1
    - setuptools
    - pip

test:
  imports:
    - datasette
  commands:
    - pip check
    - datasette --help
  requires:
    - pip

about:
  home: https://datasette.io/
  summary: An open source multi-tool for exploring and publishing data
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/simonw/datasette
  doc_url: https://docs.datasette.io/en/stable/
  description: |
    Datasette is a tool for exploring and publishing data. It helps people take
     data of any shape or size and publish that as an interactive,
     explorable website and accompanying API. Datasette is aimed at data
     journalists, museum curators, archivists, local governments and anyone else
     who has data that they wish to share with the world. It is part of a wider
     ecosystem of tools and plugins dedicated to making working with structured
      data as productive as possible.

extra:
  recipe-maintainers:
    - thewchan
