{% set name = "datasette" %}
{% set version = "0.63.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette-{{ version }}.tar.gz
  sha256: fc6a37c73d0d08e9240211a24893eb09886b84427be1ad2295a67be231175af3

build:
  entry_points:
    - datasette = datasette.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - aiofiles >=0.4,<0.9
    - asgi-csrf >=0.9
    - asgiref >=3.2.10,<3.6.0
    - click >=7.1.1,<8.1.0
    - click-default-group-wheel >=1.2.2
    - httpx >=0.20
    - hupper ~=1.9
    - itsdangerous >=1.1,<3.0
    - janus >=0.6.2,<1.1
    - jinja2 >=2.10.3,<3.1.0
    - markupsafe
    - mergedeep >=1.1.1,<1.4.0
    - pint ~=0.9
    - pluggy >=1.0,<1.1
    - python >=3.7
    - python-baseconv ==1.2.2
    - pyyaml >=5.3,<7.0
    - uvicorn ~=0.11

test:
  imports:
    - datasette
    - datasette.publish
    - datasette.utils
    - datasette.views
  commands:
    - pip check
    - datasette --help
  requires:
    - pip

about:
  home: https://datasette.io/
  summary: An open source multi-tool for exploring and publishing data
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/simonw/datasette
  doc_url: https://docs.datasette.io/en/stable/
  description: |
    Datasette is a tool for exploring and publishing data. It helps people take
     data of any shape or size and publish that as an interactive,
     explorable website and accompanying API. Datasette is aimed at data
     journalists, museum curators, archivists, local governments and anyone else
     who has data that they wish to share with the world. It is part of a wider
     ecosystem of tools and plugins dedicated to making working with structured
      data as productive as possible.

extra:
  recipe-maintainers:
    - thewchan
